Template Deal.II Application: nmpdeProject::HeatEquation< dim > Class Template Reference
nmpdeProject::HeatEquation< dim > Class Template Reference
Public Member Functions
HeatEquation ()
void run ()
Private Member Functions
void setup_ode ()
void assemble_ode_matrices ()
void assemble_ode_explicit_part (const double t)
void solve_ode ()
void output_results (const Vector< double > &sol, const unsigned int step_no) const
Private Attributes
Triangulation< dim > triangulation
FE_Q< dim > fe
DoFHandler< dim > dof_handler
SparsityPattern sparsity_pattern
SparseMatrix< double > mass_matrix
SparseMatrix< double > jacobian_matrix
Vector< double > solution
Vector< double > explicit_part
const unsigned int initial_global_refinement = 3
double initial_time = 0.0
double final_time = 0.5
const double min_step = 1e-6
unsigned int nsteps = 100
const double gamma = 20
Detailed Description
template<int dim>
class nmpdeProject::HeatEquation< dim >
Definition at line 69 of file project.cc.
Constructor & Destructor Documentation
HeatEquation()
template<int dim> nmpdeProject::HeatEquation< dim >::HeatEquation ()
Definition at line 192 of file project.cc.
References triangulation.
Member Function Documentation
assemble_ode_explicit_part()
template<int dim> void nmpdeProject::HeatEquation< dim >::assemble_ode_explicit_part (const double t) private
Definition at line 330 of file project.cc.
References FEFaceValues< int dim, int spacedim >::dof_indices(), FEValues< int dim, int spacedim >::dof_indices(), FEFaceValues< int dim, int spacedim >::JxW(), FEValues< int dim, int spacedim >::JxW(), FEFaceValues< int dim, int spacedim >::normal_vector(), FEFaceValues< int dim, int spacedim >::quadrature_point(), FEValues< int dim, int spacedim >::quadrature_point(), FEFaceValues< int dim, int spacedim >::quadrature_point_indices(), FEValues< int dim, int spacedim >::quadrature_point_indices(), FEFaceValues< int dim, int spacedim >::reinit(), FEValues< int dim, int spacedim >::reinit(), Function< int dim, typename RangeNumberType >::set_time(), FEFaceValues< int dim, int spacedim >::shape_grad(), FEFaceValues< int dim, int spacedim >::shape_value(), FEValues< int dim, int spacedim >::shape_value(), update_gradients, update_JxW_values, update_normal_vectors, update_quadrature_points, update_values, nmpdeProject::BoundaryValues< dim >::value(), and nmpdeProject::RightHandSide< dim >::value().
assemble_ode_matrices()
template<int dim> void nmpdeProject::HeatEquation< dim >::assemble_ode_matrices () private
Definition at line 238 of file project.cc.
References FEFaceValues< int dim, int spacedim >::dof_indices(), FEValues< int dim, int spacedim >::dof_indices(), FEFaceValues< int dim, int spacedim >::JxW(), FEValues< int dim, int spacedim >::JxW(), FEFaceValues< int dim, int spacedim >::normal_vector(), FEFaceValues< int dim, int spacedim >::quadrature_point_indices(), FEValues< int dim, int spacedim >::quadrature_point_indices(), FEFaceValues< int dim, int spacedim >::reinit(), FEValues< int dim, int spacedim >::reinit(), FEFaceValues< int dim, int spacedim >::shape_grad(), FEValues< int dim, int spacedim >::shape_grad(), FEFaceValues< int dim, int spacedim >::shape_value(), FEValues< int dim, int spacedim >::shape_value(), update_gradients, update_JxW_values, update_normal_vectors, update_quadrature_points, and update_values.
output_results()
template<int dim> void nmpdeProject::HeatEquation< dim >::output_results (const Vector< double > & sol, const unsigned int step_no) const private
Definition at line 537 of file project.cc.
References DataOut< int dim, int spacedim >::add_data_vector(), DataOut< int dim, int spacedim >::attach_dof_handler(), DataOut< int dim, int spacedim >::build_patches(), Utilities::int_to_string(), DataOutBase::write_pvd_record(), and DataOut< int dim, int spacedim >::write_vtu().
run()
template<int dim> void nmpdeProject::HeatEquation< dim >::run ()
Definition at line 563 of file project.cc.
References GridGenerator::hyper_L(), VectorTools::interpolate(), and triangulation.
Referenced by main().
setup_ode()
template<int dim> void nmpdeProject::HeatEquation< dim >::setup_ode () private
Definition at line 200 of file project.cc.
References DoFTools::make_sparsity_pattern(), and triangulation.
solve_ode()
template<int dim> void nmpdeProject::HeatEquation< dim >::solve_ode () private
Definition at line 417 of file project.cc.
References b(), e(), SUNDIALS::ARKode< typename VectorType >::explicit_function, SUNDIALS::ARKode< typename VectorType >::implicit_function, PreconditionSSOR< typename MatrixType >::initialize(), SUNDIALS::ARKode< typename VectorType >::jacobian_times_vector, SUNDIALS::ARKode< typename VectorType >::mass_times_vector, SUNDIALS::ARKode< typename VectorType >::output_step, SolverCG< typename VectorType >::solve(), SUNDIALS::ARKode< typename VectorType >::solve_mass, and SUNDIALS::ARKode< typename VectorType >::solve_ode().
Member Data Documentation
dof_handler
template<int dim> DoFHandler<dim> nmpdeProject::HeatEquation< dim >::dof_handler private
Definition at line 87 of file project.cc.
explicit_part
template<int dim> Vector<double> nmpdeProject::HeatEquation< dim >::explicit_part private
Definition at line 98 of file project.cc.
fe
template<int dim> FE_Q<dim> nmpdeProject::HeatEquation< dim >::fe private
Definition at line 86 of file project.cc.
final_time
template<int dim> double nmpdeProject::HeatEquation< dim >::final_time = 0.5 private
Definition at line 105 of file project.cc.
gamma
template<int dim> const double nmpdeProject::HeatEquation< dim >::gamma = 20 private
Definition at line 113 of file project.cc.
initial_global_refinement
template<int dim> const unsigned int nmpdeProject::HeatEquation< dim >::initial_global_refinement = 3 private
Definition at line 101 of file project.cc.
initial_time
template<int dim> double nmpdeProject::HeatEquation< dim >::initial_time = 0.0 private
Definition at line 104 of file project.cc.
jacobian_matrix
template<int dim> SparseMatrix<double> nmpdeProject::HeatEquation< dim >::jacobian_matrix private
Definition at line 94 of file project.cc.
mass_matrix
template<int dim> SparseMatrix<double> nmpdeProject::HeatEquation< dim >::mass_matrix private
Definition at line 93 of file project.cc.
min_step
template<int dim> const double nmpdeProject::HeatEquation< dim >::min_step = 1e-6 private
Definition at line 106 of file project.cc.
nsteps
template<int dim> unsigned int nmpdeProject::HeatEquation< dim >::nsteps = 100 private
Definition at line 110 of file project.cc.
solution
template<int dim> Vector<double> nmpdeProject::HeatEquation< dim >::solution private
Definition at line 97 of file project.cc.
sparsity_pattern
template<int dim> SparsityPattern nmpdeProject::HeatEquation< dim >::sparsity_pattern private
Definition at line 92 of file project.cc.
triangulation
template<int dim> Triangulation<dim> nmpdeProject::HeatEquation< dim >::triangulation private
Definition at line 85 of file project.cc.
The documentation for this class was generated from the following file:
/github/workspace/source/project.cc